query($id: Int!) {
  User(id: $id) {
    name
    createdAt
    statistics {
      anime {
        count
        meanScore
        standardDeviation
        minutesWatched
        episodesWatched
      }
    }
  }
  MediaListCollection(userId: $id, type: ANIME) {
    lists {
      name
      status
      entries {
        id
        status
        score(format: POINT_10)
        progress
        completedAt {
          year
          month
          day
        }
        media {
          id
        }
      }
    }
  }
}